### ISSUE TITLE
support kie custom label

### ISSUE THREAD

**Issue by liweiv** [go-chassis/go-chassis#1027]
I used kie as the config server. I wanna add custom labels, such as project,product. but there are no way to setting custom labels in config file. however this feature had finished in spring cloud huawei config（only one label）. 
spring-cloud-huawei-config:
```yaml
kie:
  customLabel: labelKey
  customLabel: labelValue
```
expect go-chassis supporting
```
kie:
  customLabels:
    - key: labelKey
      value: labelValue
    - key: labelKey2
      value: labelValue2 
```
