### ISSUE TITLE
内存无限制增长

### ISSUE THREAD

**Issue by tomlee0201** [go-chassis/go-chassis#304]
我们用go-chassis做了个demo进行压力测试，在吞吐量5000左右持续测试，内存一直在增长，最后达到10G以上，测试停止后内存还是维持在高位。

测试demo分三部分，api对外提供接口，restserver和rpcserver提供服务，api接收到请求后请求server，然后把server的结果返回去。测试时，每个服务启动一个，然后jmeter调用api暴露的http接口。具体代码在https://github.com/tomlee0201/chassisdemo

另外抓取了一个prof文件

[pprof002.svg.zip](https://github.com/go-chassis/go-chassis/files/2244993/pprof002.svg.zip)

请帮我们确认哪里出了问题，如果有需要补充的信息请提出来

**Comment by tianxiaoliang** [comment]
你观测的是哪个内存值 VIRT 还是RES

**Comment by tianxiaoliang** [comment]
https://github.com/go-chassis/go-chassis/tree/master/benchmark
这是我们的压测工具，压测过程内存是不会增长的，我会看下你们的工具，不过请试用下我们的先

**Comment by tomlee0201** [comment]
问题找到了
使用https://go-chassis.readthedocs.io/en/latest/getstarted/writing-rest.html 这里示例的配置文件
```
cse:
  service:
    registry:
      address: http://127.0.0.1:30100 
  protocols: # what kind of server you want to launch
    rest: #launch a http server
      listenAddress: 127.0.0.1:5001
```

没有配置handler.chain，就会使用默认的配置，默认配置里有tracing-provider，但是我既没有配置tracing属性，也没有安装zipkin，在压力测试情况下，tracing内不断堆积信息，导致内存不停增长
我加上个别的hander.chain就没有问题了
建议，默认的配置去掉tracing-provider，或者tracing-provider能够正确处理没有配置tracing的情况
