### ISSUE TITLE
kube example fix

### ISSUE THREAD

**Issue by marchtea** [go-chassis/go-chassis#431]
Hi, example link in `go-chassis/docs/discovery/kube-discovery.md` is gone as the repo has been moved to `go-chassis/go-chassis-examples/kube`. Plz update docs.
Also, I tried example in `go-chassis-examples` to run my app in kube, but got stuck by the missing config in kube config.
As  `go-chassis/go-chassis-examples/kube/server/build/k8s/kubeserver-v1.yaml` shows,  it maps a config (kube-config) as `/etc/.kube`, but how to config that? 
```
        volumeMounts:
        - mountPath: /etc/.kube
          name: kube-config
          readOnly: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: kube-config
        name: kube-config
```

**Comment by tianxiaoliang** [comment]
will investigate

**Comment by crystaldust** [comment]
@marchtea The kubeconfig file is needed to let go-chassis call kube-apiserver, you can deploy the ConfigMap `kube-config`  with the kubeconfig content, here is an example:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-config
data:
  config: |
    apiVersion: v1
    clusters:
    - cluster:
        certificate-authority-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUZtakNDQTRLZ0F3SUJBZ0lVU0RQdmZoTDMzNGtLSDhxN3JnbE9nSDZ3aXVZd0RRWUpLb1pJaHZjTkFRRU4KQlFBd1pURUxNQWtHQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbAphVXBwYm1jeEREQUtCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByCmRXSmxjbTVsZEdWek1CNFhEVEU0TURreU9UQXpNemt3TUZvWERUSXpNRGt5T0RBek16a3dNRm93WlRFTE1Ba0cKQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbGFVcHBibWN4RERBSwpCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByZFdKbGNtNWxkR1Z6Ck1JSUNJakFOQmdrcWhraUc5dzBCQVFFRkFBT0NBZzhBTUlJQ0NnS0NBZ0VBcGRaUXZ0WjFZeDI5bjdOcllKczYKeHl5ZitMT0cxOHpiZ0kvZ0s1bzNZQm8vNXA5QTYrcFJ2Z2thS1FDeDB3VC9tOWZrQ1pvOFpuazI1NDVmSnBPSApRRW0wKzk4blZ1SEQvTkt4T2UxZ0ozT3B0Y05GM3R6TXR3VUlnMzE0K0Y1Y2JRb3RCeWNIWGN4NWF5K1M0cndiCnpDcjArTkl6am1zeVFRbmg4aXRRMVo0VFBQK3hSaXZYM2RjdmtqdTZYQktwTE82UUVTazN0ZGFmZEJrMDVDaFIKbFgwVDVaKzVudnUrdjNKaGFTdFFrY2FqYVp4a2pBbGtLZ3NMRHJZWU9RSnczVDBxT2p4UVRyMWdIakFBcWFWRApuSmFNTlFJTFpUMFpoYXVzL0d5NmhLaGN4WWJoLzlkY0FSdVQrcmNyUGt1dGgyY0VkTVNiQTVPUC9jckNhbjdQCjBlVndoaVJFNElnaGxuU3JOY2ZsNmdaQlVRaXRXSHU0MWZFK0hOZjJvaXV0S29BQjJ2Mnl3TG1TWU01V3VIZGQKbWVvTHRuK21NOTBVaWtTeU5HZStXL1NTRlQ3VnlNK3dhdldBbUZuRnJqWkYxRUtPajJKQXlxSzY1VWxpYUJCTApYbFhIMUVDVVEweGVTNTlEOTBXY0RsSXVQb0NYeDRFZ3FSdUcxN0xmT0ltMnJnRGxMa0RFdHA1RzV1REZZcWJDCm5sbytTZkZaUllDSElXZE1PVmhhOWVXR3U2K2VtcUtaZkh6bHFQNVpDbDJMdHRPNFAvNDZCOHdiOU1KSmMzZG4KTXRqRGVxazNobjNIeHptYWc2VHZGSEJzSVROVjZLQWp4NUVJd1Z1RTBibEhtM25rcGJ4M2pZV0pEVzY3NlhEMwpReFo4MXU3WlI3WkhjazBIa1VSY3FOOENBd0VBQWFOQ01FQXdEZ1lEVlIwUEFRSC9CQVFEQWdFR01BOEdBMVVkCkV3RUIvd1FGTUFNQkFmOHdIUVlEVlIwT0JCWUVGSlk3SFR0aUczZFlySWFtMTBxVW1SZDZzUXBpTUEwR0NTcUcKU0liM0RRRUJEUVVBQTRJQ0FRQjFZa1Z5S0pKOURMdlFnMTNDalRhZUg1YVlYbDg2d2pTcXR5WUorNitZdWFCWgpETEFjaVdpYTc2cW1YR0hPUnNNKzNqWlFzN3cvTVdHTnRlSDF5RFRhZXo4d3hueHJCZzVTK1djaXZ1QlBlNmlwCnlJSGlFb25CSFNwQUwydFFqSG9MMHlwT0dzei9UdC9YWWVqOElZM2ViVC9XRHN6Q012RVFaQ3lQVVZYbTQvdmYKQ0ZZcnZZSlNnOVo1c0x1Zk8yNm9wbEd2RXFZTFk5UWJEL0FzRklta2tDNndldWxGS1NqdHFrUDdzZ2N4eDRrKwpkZnozbFUybDUvaUJDak5VclExd3M3NHpOQjVaUm5vZzhvZG9SQ3hac2MyaU1UV3V3THNkZC94VWdyemRucEpGClF3WVdGOWVUNktyS2ZpUFMyRGNGU0Jvc3ZkN0tVZktxbjkxSzI3b1Y3MEVkeGtaeGZCajdtajRaZGQxT1lBZFAKVlFLaFgxdnY4WEMvUERHakk5dkZuR012Wm5GMEpRUFpIY2MxbnRVcG9keENQV1kyWUdKMlRVek5MMWJTdEZkUAo1V2RsRWF1azBoRzljdjZTa2d0cGxpNGRUdUZmZkZqWmw1UUJUUzlsTjFuNXhlL25JQjVwT0xyWlFyajhrelJNCnNFVGJ2bzQvdEVZUmpkQVpYV3VRRnhoc0EyQXlWdklLaU1EUW5jRTU5V2pUdnlGV3AzcWZyVWQvUEhrTndWQ1AKL3MzNGdyR3Exb2ZuMXh5MG9hVjdSYytLWnpXM3hJcXlQVDFIRWlXQ0pJakt1bnVPT0QyQldOaUxMbDBZN3kxTQpuMkVHMjNxWFBMTTd5T3FNVjJOQStqcGx3elorbmR6WjVvQldSeWwybURKTUpuV3d6NEYvNUlDUzV1Rlp0QT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        server: https://192.168.43.80:6443
      name: kubernetes
    contexts:
    - context:
        cluster: kubernetes
        user: admin
      name: kubernetes
    current-context: kubernetes
    kind: Config
    preferences: {}
    users:
    - name: admin
      user:
        client-certificate-data: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUUzVENDQXNXZ0F3SUJBZ0lVYXpoaWVJL0F5L1dkekEvck16VmdQd2phQkpnd0RRWUpLb1pJaHZjTkFRRU4KQlFBd1pURUxNQWtHQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbAphVXBwYm1jeEREQUtCZ05WQkFvVEEyczRjekVQTUEwR0ExVUVDeE1HVTNsemRHVnRNUk13RVFZRFZRUURFd3ByCmRXSmxjbTVsZEdWek1CNFhEVEU0TURreU9UQXpOREV3TUZvWERURTVNRGt5T1RBek5ERXdNRm93YXpFTE1Ba0cKQTFVRUJoTUNRMDR4RURBT0JnTlZCQWdUQjBKbGFVcHBibWN4RURBT0JnTlZCQWNUQjBKbGFVcHBibWN4RnpBVgpCZ05WQkFvVERuTjVjM1JsYlRwdFlYTjBaWEp6TVE4d0RRWURWUVFMRXdaVGVYTjBaVzB4RGpBTUJnTlZCQU1UCkJXRmtiV2x1TUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUF0QmdkWXFQZy8vOWkKN3FsL3ZQcGg4MlVmR0xJZExMUGl2S0g2b0JIMmVWSjNhR1dvZE92OXVNWXpHT1Y4REsyUGVVT3UyNHM5RE1oVgpaaHlXY05zbVYvSVQyalM4S2JLVk9ZZGpnZGdEWFNVUHdJK0ttVkR4ZFVpVU5CNE5ZQmkwdW9WcExsNlRDTmJ2Ck81c0gzajNPZ2tmbGZONkxvSGdFMjZmR3NBYzVkUWJhSlBaWktVSDBWT1lUSWk1a2VMUGI2eEtndjJtZDd6RVAKZzFKUk1zcVI0TllLcG5teWVHbUcyNUZicDZZeExCTnF1YTBFMmVKT2ZqNU0yenFGQWxqeHFIZXBhKy9iVSs3MQpmMWNpNVZsSVZTcVlkcDdmM2VqRElXRWExbGVxSmR6bkV6bklkSm8vcmVWZS9qbTdKczM4aFBLbThLVXZ6bzJ5CjNkZndCUFpxN1FJREFRQUJvMzh3ZlRBT0JnTlZIUThCQWY4RUJBTUNCYUF3SFFZRFZSMGxCQll3RkFZSUt3WUIKQlFVSEF3RUdDQ3NHQVFVRkJ3TUNNQXdHQTFVZEV3RUIvd1FDTUFBd0hRWURWUjBPQkJZRUZDVElERTNBN0tjbApJendXU0JGNVQxbFJzU2J5TUI4R0ExVWRJd1FZTUJhQUZKWTdIVHRpRzNkWXJJYW0xMHFVbVJkNnNRcGlNQTBHCkNTcUdTSWIzRFFFQkRRVUFBNElDQVFBVjJFN3NjS3loTmpFSXkySTg3eTNFc2plajVQMFh5WkJBcitUTmFTUnUKVnlpNUlhS1dRTzYxK2k0eVY3MnJJcTQ0VjlIblhrN3lSVkNOVmxQQkZMVnVyK0pneTk0eUVnU1pBTDRmRkNUUwpPREFtckRZM3dtVUF2VHdZSmpoODRnZ0dkRDduWUZkaTFucmFpSTVOcEhNMHA1QSt2WlZWUm1wSnh1a3JQK2M4ClpMK3NoeFZ0T25PaXhPVCtnVXBCc2dvY1JRalNJSkNtQjBEczZiZUhKNWVZa0hyWGN1d0hOcWYwOHYwck1yTVoKaHdnWUJFNmdIWklEUmwxeVhWMnZ5WHhPd2ZrRXBmWG4xcDdFc0lvSEdZQ1lQaUlubVlqWEN2S0c2TGV6ay9adAppRWc3cG55Rmx0d0lWREFmL2YydENwckNaejViN1B5Uitjc3ZmbldLZE95cllNTWdrMU05aVFCODMzL2tKSGplCnVTazlmdERBWnpocG14OGt0aHRuTm5JYWFLdUoxdEM3NTFuSnBtUTRaMmxDYlYzRjFGckFQTkhuQTFmcFFpNWkKckwyY2tDMm1kQkpOUjVRQ3l6TkJPR1d0cFplNkJiVDVnMVJ5bVo5ZUE0ak90cng4RFVJVGczR0pPb21TTGU4bgo3MDVaUEdDYTZRRE5wSkVnSVpwcXpyVzdwRmsvVTdlS014TmtHT3FXY1F6RllRQ1dzbDJTNy9tSEpxTStSaHM4CkJHRU9nNGxTY2RoTlQxWnBaT2pXelJsZDZEdGZKOSswRk9YZGZIeW1PTmN1dFNzWlEvQWJYUm1WclRCNDVmcEoKTkZzaENjTk1kdGEyc3NHV1pjM2grR29YUHFzK3kyUGloc1ErL1RtKy8zMWxFZ1FiclA1SUNiVFdoRjhSQ3FlbAp0UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
        client-key-data: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFb3dJQkFBS0NBUUVBdEJnZFlxUGcvLzlpN3FsL3ZQcGg4MlVmR0xJZExMUGl2S0g2b0JIMmVWSjNhR1dvCmRPdjl1TVl6R09WOERLMlBlVU91MjRzOURNaFZaaHlXY05zbVYvSVQyalM4S2JLVk9ZZGpnZGdEWFNVUHdJK0sKbVZEeGRVaVVOQjROWUJpMHVvVnBMbDZUQ05idk81c0gzajNPZ2tmbGZONkxvSGdFMjZmR3NBYzVkUWJhSlBaWgpLVUgwVk9ZVElpNWtlTFBiNnhLZ3YybWQ3ekVQZzFKUk1zcVI0TllLcG5teWVHbUcyNUZicDZZeExCTnF1YTBFCjJlSk9majVNMnpxRkFsanhxSGVwYSsvYlUrNzFmMWNpNVZsSVZTcVlkcDdmM2VqRElXRWExbGVxSmR6bkV6bkkKZEpvL3JlVmUvam03SnMzOGhQS204S1V2em8yeTNkZndCUFpxN1FJREFRQUJBb0lCQUdlaHVNY2FKazhwVm5TZgpkTEg2SW9NOG5UaEl4aUVESW1ZSmozNnMxM2ZZekgxMmdnbEdBeXBnWXViZ3B4RmtqanJwaDZVdDZtT0FwQ091Ckw2T2hkOThEbmdqaWI2Uk83eSs3aUxjZTVsQ2pFdjFybkFXOVhqUnZIMWtlTWZRcVExVlJqOFR2Qnd6L0lZcmIKR3h2MzFPMkRFYnRaRkYreXNKajFZby9JbUhlT0VmanZPb0tYZCtuUnViNUVtbW9uZmtLZDdtTmVCLzF5VXd2VwprRXY5aHQ5cFREYW5KeFNhYW1GYU1GNnZDSEpoUGpXcDRrOVlWRm9TSXhlSDBwMXRqWjl1ZVNsVmp2T3Mxa3JsCmhzQk8wRXVVeldTcHgxbm16Lzd2RHg3K3Y2QlV6TkRFN1N6S25RU0x4UGJQWkNZLzVRbWFnWjd3eVJ5aklKUHkKRFBOSHZBRUNnWUVBNkQ5cXYrVmo0UTBKVHVFSElsYVhQT0c2ZmlGbWJpNzlIYXBVdFU2UDRDK1JST1AxUGwySAorWGVpS3VjZmY4Y0hCRzZQM3duUFZoMXlVbUNhcE9kSU40a1J6TDdicTJIc044ZTBLSkp3WnVnUkZjVWdZd0RNCi91VTRValcvS0lIRDRtamlXdy94d0xrMTA5NGMzRlpKelh2RzVsbU9FMnU5NEpleXVnQTNFRkVDZ1lFQXhvTSsKSW00MmhmZUlQZWFVNWUzMisvQzNEa3hBWGZFZUFHb0lLNjFsQ0pwMWRlNE1WK1Qvd09iSUZBU2hYUDQ4TDJXcgpSSHpOK2VIa3B4dURyUVdxNGNsbk56UytweU9zM3BNUUE0UXVteFZPV0EyTWhwMGw2TENaTmdOeW5DWVR0eS9RCmkxdk94UVJFSzJ1UnFjWDBGalVwZ1B6WUQ1WlIyWURIUVVjdnhkMENnWUVBb2wxYml1YWFxZ1pNSUpvUE84RmYKb0ErTEtveTlLSUN2TWlNWGIxMktGa2dLL2llRUYyS2FJaHl5QWQ1czFnN1ZhQkxIZ0QxQ2QwakUyTFJ5eUtCcwppMjdIUStXV2V6MU5RRDNjUkpVRUFkMXh2RStBOGRYb2VyYlRaaDN2RXltTlFXYmtBSmVvQW4wNUZYSnRxTmltClpnS0hyaGlqekE0Qnc5Y3Ard0VWZmRFQ2dZQWRQVFdJc3IwYkxHT0g0bytwOGt2L3Zldm9ramlrM1oveXBhdUEKYTNESFBLRHlkdGFnbDUxSUYzWCs1Tk96czhxL25IVUdpRzk2VDloeStLMkRiYU5HMEhpQWZDZGN6UGRvYlRiZApuYm1UcENhKzkzZnNWL2MrZDh5SlZTYXJjenhTTGh2RWV3aFFvcGs3NEFNN2cybTVYNmsyVTRlcmZCT2dPc1NlCmk5S3dqUUtCZ0RwcW02TEd5eFpUb3pOOXFackxwZDRBMEQzOUVNS3NtZnlIaXhxZmZkUXVTZUY0VTd2ekpPb0IKK3djMElWdTc1bERKbldsS3M2YlVBMjh6WFNOcnhiT2FIQjdJMXZ5Y2xtZEE5V0xWZ0JSWWNhWkIxcGZ4SnJqRwowU2s1bUVOZmNCait3QVZHRUdET2VmMGJwZkF4V25JUXUzT1o4WldESEJINkRLU2dYWUJxCi0tLS0tRU5EIFJTQSBQUklWQVRFIEtFWS0tLS0tCg==
```

Take care of the indents,  the kubeconfig file content after `config: |` should be intended with 2 more spaces.
