### ISSUE TITLE
how to register paths into SC

### ISSUE THREAD

**Issue by daqingshu** [go-chassis/go-chassis#432]
1. current register, have not registe paths info to SC， and other microservice can not find it.

2. both chassis.yaml microservice.yaml  can have APPLICATION_ID item, which is the effetive ?

In our case,  we dynamic generate chassis.yaml file before init go-chassis,  the listening IP address and port and SSL config and SC address are passed from deploy phase
use microservice.yaml store static info

**Comment by daqingshu** [comment]
> what is path？
plz ref 
https://github.com/apache/servicecomb-service-center/blob/master/server/core/proto/services.pb.go#L535

**Comment by tianxiaoliang** [comment]
ServicePath？

**Comment by tianxiaoliang** [comment]
ok， will implement that

**Comment by daqingshu** [comment]
can it be in microservice.yaml ? as is struct in ServiceCenter
``` yaml
APPLICATION_ID: nce
service_description:
  name: DemoService     # name your provider
  version: 1.0.1
paths:
- path: /rest/demoservice
  property:
    checksession: true
```

**Comment by tianxiaoliang** [comment]
will looks like
```yaml
APPLICATION_ID: nce
service_description:
  name: DemoService     # name your provider
  version: 1.0.1
  paths:
  - path: /rest/demoservice
    property:
      checksession: true
```
