### ISSUE TITLE
同时为grpc客户端和服务端使 客户端无法访问其他grpc微服务

### ISSUE THREAD

**Issue by wksw** [go-chassis/go-chassis#661]
**Describe the bug**
我本身服务是个server端，用客户端的方式去访问其他微服务报错
**Version of go chassis**
v1.5.0
**To Reproduce**
// 这个是服务端代码
```golang
func main() {
	chassis.RegisterSchema("grpc", &schemas.Login{}, server.WithRPCServiceDesc(&pb.Login_serviceDesc))
	if err := chassis.Init(); err != nil {
		lager.Logger.Errorf("Init chassis FAIL[%s]", err.Error())
		return
	}
	chassis.Run()
}
```

// 然后我想在这里去访问别的微服务
// 出现do not support [grpc] client" 错误
```golang
func getToken(ctx context.Context, in *auth.TokenReq) (*auth.TokenResp, error){

	// md, _ := metadata.FromIncomingContext(ctx)
	cx := common.NewContext(map[string]string{
		"X-SUB-TOKEN": "XXX",
	})
	reply := &auth.TokenResp{}
	err := core.NewRPCInvoker().Invoke(cx,
		archaius.GetString("microservice.auth_microservice.service_name", "auth_microservice"),
		archaius.GetString("microservice.auth_microservice.schema", "auth.Auth"),
		"GetToken",
		in,
		reply,
		core.WithProtocol("grpc"))
	return reply, err
}
```

// 账户密码登陆
```golang
func (lg *Login) LoginWithPassword(ctx context.Context, in *pb.LoginWithPasswordReq) (*pb.LoginResp, error){
       var tokenReq = auth.TokenReq{
		Uid: "xxx-xxx-xxx",
		DeviceId: in.DeviceId,
		LoginType: auth.LoginType_PASSWORD,
		AppId: "xxx-xxx-xxx",
	}
	token, err := getToken(ctx, &tokenReq)
}
```
**Logs**
{"level":"WARN","timestamp":"2019-07-15 08:44:12.139 +00:00","file":"servicecenter/servicecenter.go:327","msg":"b18a9e9e059d7676840a8aa141145700b2cd74e0 Get instances f
{"level":"INFO","timestamp":"2019-07-15 08:44:12.155 +00:00","file":"client/client_manager.go:104","msg":"Create client for grpc:auth_microservice:192.168.35.131:9092"}
{"level":"ERROR","timestamp":"2019-07-15 08:44:12.155 +00:00","file":"client/client_manager.go:66","msg":"do not support [grpc] client"}
{"level":"ERROR","timestamp":"2019-07-15 08:44:12.155 +00:00","file":"handler/transport_handler.go:27","msg":"GetClient got Error: don't have client plugin grpc"}

**Comment by tianxiaoliang** [comment]
https://github.com/go-chassis/go-chassis-protocol

如文档所述，你需要import client 插件

import _ "github.com/go-chassis/go-chassis-protocol/client/grpc"

**Comment by tianxiaoliang** [comment]
你好，可否愿意将本次实践写成一个博文分享，题目是使用go chassis遇到了什么错误怎么解决的，非常感谢

**Comment by wksw** [comment]
> 你好，可否愿意将本次实践写成一个博文分享，题目是使用go chassis遇到了什么错误怎么解决的，非常感谢

没问题 来个文档地址

**Comment by tianxiaoliang** [comment]
> > 你好，可否愿意将本次实践写成一个博文分享，题目是使用go chassis遇到了什么错误怎么解决的，非常感谢
> 
> 没问题 来个文档地址

你可以自行选择CSDN，掘金，知乎，简书，gitchat这样的网站分享，是博文

**Comment by wksw** [comment]
> > > 你好，可否愿意将本次实践写成一个博文分享，题目是使用go chassis遇到了什么错误怎么解决的，非常感谢
> > 
> > 
> > 没问题 来个文档地址
> 
> 你可以自行选择CSDN，掘金，知乎，简书，gitchat这样的网站分享，是博文

你好  这个问题再k8s中会出现”server closed the stream without sending trailers“， 我用的部署方案是k8s+istio+service-center这种模式的，我发现go-chassis在请求别的服务的时候是用的http/1.1， 这种只能用go-chassis直接对接istio吗？

部署文件：
```
---
apiVersion: v1
kind: Service
metadata:
  name: account-microservice
  namespace: paasport-microservice
  labels:
    app: account-microservice
spec:
  ports:
  - name: grpc-port
    port: 8080
    targetPort: 8080
  selector:
    app: account-microservice

---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: account-microservice-deployment
  namespace: paasport-microservice
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: account-microservice
        version: 0.0.1
    spec:
      containers:
      - image: dockerhub.contoso.com/paasport/account_microservice:0.0.1
        imagePullPolicy: Always
        name: account-microservice
        env:
          - name: CONFIGOR_KEY
            valueFrom:
              secretKeyRef:
                name: account-secret
                key: key
          - name: CONFIGOR_ENV
            value: production
          
        ports:
        - containerPort: 8080
          name: grpc-port
        volumeMounts:
          - name: chassis
            mountPath: /workspace/conf/

      volumes:
        - name: chassis
          configMap:
            name: account-config
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: account-microservice
  namespace: paasport-microservice
spec:
  host: account-microservice
  subsets:
  - name: v1
    labels:
      version: 0.0.1
  - name: v2
    labels:
      version: 0.0.2
  - name: v3
    labels:
      version: 0.0.3

---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: account-microservice
  namespace: paasport-microservice
spec:
  hosts:
    - account-microservice
  http:
  - route:
    - destination:
        host: account-microservice
        subset: v1
        ```
配置文件：
APPLICATION_ID: paasport-microservice
    cse:
      config:
        client:
          # 配置中心地址
          serverUri: http://service-apollo-config-server-dev.paasport:8080
          # 配置中心类型
          type: apollo
          enabled: true
          # 配置刷新类型
          refreshMode: 1
          # 配置刷新间隔
          refreshInterval: 10
          serviceName: apollo-iam-config
          env: DEV
          cluster: default
          namespace: application
          token: xxx
          instance: 10.0.0.1
      # metrics:
      #   apiPath: /metrics
      #   enable: true
      #   enabledGoRuntimeMetrics: true
      service:
        registry:
          address: http://service-center.paasport:30100
      protocols:
        grpc:
          listenAddress: 0.0.0.0:8080
          advertiseAddress: 0.0.0.0:8080
