### ISSUE TITLE
细粒度流量治理框架，且可定制的扩展治理定义

### ISSUE THREAD

**Issue by tianxiaoliang** [go-chassis/go-chassis#754]
为了能够更好地治理每个流量，比如针对某个特殊流量进行治理（例如限流，跟踪），需要一种模块设计，能够承载这种治理需求

**Comment by tianxiaoliang** [comment]
我们可以通过chain里的一个handler对流量进行标记，标记方式是当请求match一定规则，如下：
```yaml
servicecomb:
  match:
    match-user-json: |
        headers:
          cookie:
            regex: "^(.*?;)?(user=jason)(;.*)?$"
          user:
            equal: jason
        apiPath:
          contains: "some/api"
        method: GET
```

那么请求就被打上了 match-user-json这样的记号

当遇到处理限流规则的handler后，就会生效，比如：
```yaml
servicecomb:
  rateLimiting:
    limit-json: |
        match: match-user-jason
        quota: 5000
```
