### ISSUE TITLE
路由管理模块match规则统一

### ISSUE THREAD

**Issue by tianxiaoliang** [go-chassis/go-chassis#827]
# 需求背景：

1.x的路由规则使用自己match代码逻辑进行流量匹配，如下
https://go-chassis.readthedocs.io/en/latest/user-guides/router.html

并且老的支持match模板，如下

```yaml
servicecomb:
    routeRule: 
      Carts: |
        - precedence: 2
          match:
            refer: request-with-special-header
          route:
            - weight: 100           
              tags:            
                version: 2.0
    sourceTemplate:
      request-with-special-header:
        source: vmall
        headers:
          cookie:
            regex: "^(.*?;)?(user=jason)(;.*)?$"
```

既然我们已经有了新的core/match模块并且支持开发者自定义不同的match匹配，规则，name应当将框架的所有match逻辑收编到该pkg的逻辑中，保证方案统一

# 用户故事：
目前路由的match支持，正则，等于，大于，小于等算子，现在有人提出希望是取值范围，我们作为框架维护者不希望将代码放在if else去判断，而且经常接受这种定制需求，而是允许用户安装算子，match模块提供算法完成路由匹配阶段任务

核心代码
https://github.com/go-chassis/go-chassis/blob/master/core/match/match.go
```go
var matchPlugin = map[string]Method{
	"exact":    exact,
	"contains": contains,
	"regex":    regex,
}

//Install an operator
func Install(name string, m Method) {
	matchPlugin[name] = m
}
```
允许用户自定义算子

# 需求描述
路由规则允许引用一个match规则定义 https://github.com/go-chassis/go-chassis/issues/754
``` yaml
          match:
            refer: request-with-special-header
```
