### ISSUE TITLE
配置规范

### ISSUE THREAD

**Issue by xy-github-issue** [go-chassis/go-chassis#859]
看到 go-chassis 里的配置，有时候用小写起始驼峰，有时候用大写驼蜂，有时候用下划线，这个没有规范吗？不计划统一一下吗？

**Comment by tianxiaoliang** [comment]
这是由于早期快速发展阶段 没有重视设计导致的，感谢建议，我一直期望能够统一，2.0可以把yaml统一为小写开头的驼峰配置，你可以提PR更改了

**Comment by tianxiaoliang** [comment]
```yaml
servicecomb:
  service:
    spec:
      app: default
      name: Server
      version: 0.1
```
这种方式统一
