### ISSUE TITLE
about lint

### ISSUE THREAD

**Issue by daqingshu** [go-chassis/go-chassis#917]
https://github.com/golangci/golangci-lint
see https://golangci-lint.run/usage/linters/ : 
Enabled By Default Linters 
deadcode - Finds unused code
errcheck - Errcheck is a program for checking for unchecked errors in go programs. These unchecked errors can be critical bugs in some cases
gosimple - Linter for Go source code that specializes in simplifying a code
govet - Vet examines Go source code and reports suspicious constructs, such as Printf calls whose arguments do not align with the format string
ineffassign - Detects when assignments to existing variables are not used
staticcheck - Staticcheck is a go vet on steroids, applying a ton of static analysis checks
structcheck - Finds unused struct fields
typecheck - Like the front-end of a Go compiler, parses and type-checks Go code
unused - Checks Go code for unused constants, variables, functions and types
varcheck - Finds unused global variables and constants

and go-chassis use which linters

**Comment by daqingshu** [comment]
already used, ignore it.

**Comment by tianxiaoliang** [comment]
你的意思是什么，要如何改脚本

**Comment by daqingshu** [comment]
> 你的意思是什么，要如何改脚本

看当前的PR，没发现什么lint的错误，但是本地做的话，如果用默认的golangci-lint配置，有很多错误，所以想问问你，想做哪些检查

**Comment by tianxiaoliang** [comment]
```yaml
name: golangci-lint
on:
  push:
    tags:
      - v*
    branches:
      - master
  pull_request:
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.27
          args: --skip-dirs=examples --out-format=colored-line-number --enable golint --skip-files=.*_test.go$
```

目前除了跳过一些不需要的代码，都是用的默认配置，我期望就按默认即可，不过你说的情况确实存在么？我看golint门禁还是可以查出问题啊
